### ISSUE TITLE
Problem with CLI

### ISSUE THREAD

**Issue by cthoyt** [HunterMcGushion/docstr_coverage#51]
I got the following issue with the `docstr-coverage --help` on v2.0.0.

I think changing `"[{}]".format("|".join(self.choices))` to `"[{}]".format("|".join(map(str, self.choices)))` would solve this issue

```bash
docstr-coverage --help
Traceback (most recent call last):
  File "/Users/cthoyt/.virtualenvs/bel2scm/bin/docstr-coverage", line 8, in <module>
    sys.exit(execute())
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/decorators.py", line 323, in callback
    echo(ctx.get_help(), color=ctx.color)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 1024, in format_options
    rv = param.get_help_record(ctx)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 1868, in get_help_record
    rv = [_write_opts(self.opts)]
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 1865, in _write_opts
    rv += " {}".format(self.make_metavar())
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/core.py", line 1520, in make_metavar
    metavar = self.type.get_metavar(self)
  File "/Users/cthoyt/.virtualenvs/bel2scm/lib/python3.9/site-packages/click/types.py", line 161, in get_metavar
    return "[{}]".format("|".join(self.choices))
TypeError: sequence item 0: expected str instance, int found
```

**Comment by cthoyt** [comment]
On second thought, this is happening inside click. Maybe the choices shouldn't be given as integers in

https://github.com/HunterMcGushion/docstr_coverage/blob/6d30922cdc21e036e673204bb498776e33d9969a/docstr_coverage/cli.py#L154-L163

Providing a fix for this TODO would also probably solve my issue

**Comment by HunterMcGushion** [comment]
@cthoyt, thanks for bringing this up. I definitely should've checked to see that `--help` was still working after the change, but at the time it looked like it was necessary for #39 to be able to handle number options when parsing them from a YAML file. There's some discussion related to it [here](https://github.com/HunterMcGushion/docstr_coverage/pull/39#discussion_r544772168). 

As you noticed from the TODO comment, I'm all for using counting. I'm now wondering how that would work when using the YAML config, though. Thank you for opening #52 to address the problem so quickly!
