### ISSUE TITLE
AssertionError: An unexpected context occurred... with file

### ISSUE THREAD

**Issue by bjornconstructors** [HunterMcGushion/docstr_coverage#79]
When I have a file like so:

```
"""









"""


a = None

```

I get:
```
AssertionError: An unexpected context occurred during parsing of /theabovefile.py It seems not all file lines were tokenized for comment checking.
```

**Comment by MiWeiss** [comment]
Thanks for your report. I was unfortunately not capable to reproduce this issue. Do you have any additional info that may help me? 

E.g. 
- OS
- used docstr-coverage config / flags
- python version 
- docstr-coverage version

Thank you

**Comment by bjornconstructors** [comment]
@MiWeiss I think I made a small mistake in the reproduction example, please try this:
```
"""









"""


class a:
    pass
```

docstr-coverage version: 2.0.1 on Ubuntu 20.04.2 LTS with the default config flags (e.g. no `.docstr.yaml` or flags passed to the command, on Python 3.8.5:
```
docstr-coverage reproduce.py 

File: "/home/bjorn/reproduce.py"
Traceback (most recent call last):
  File "/usr/local/bin/docstr-coverage", line 8, in <module>
    sys.exit(execute())
  File "/home/bjorn/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bjorn/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bjorn/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bjorn/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docstr_coverage/cli.py", line 314, in execute
    file_results, total_results = get_docstring_coverage(
  File "/usr/local/lib/python3.8/dist-packages/docstr_coverage/coverage.py", line 254, in get_docstring_coverage
    doc_visitor.visit(parse(source_tree))
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/dist-packages/docstr_coverage/visitor.py", line 29, in visit_Module
    self.generic_visit(node)
  File "/usr/lib/python3.8/ast.py", line 371, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/dist-packages/docstr_coverage/visitor.py", line 33, in visit_ClassDef
    self._visit_helper(node)
  File "/usr/local/lib/python3.8/dist-packages/docstr_coverage/visitor.py", line 44, in _visit_helper
    has_doc = self._has_doc_or_excuse(node)
  File "/usr/local/lib/python3.8/dist-packages/docstr_coverage/visitor.py", line 54, in _has_doc_or_excuse
    return self._has_docstring(node=node) or self._has_excuse(node=node)
  File "/usr/local/lib/python3.8/dist-packages/docstr_coverage/visitor.py", line 78, in _has_excuse
    assert node_start < len(self.tokens), (
AssertionError: An unexpected context occurred during parsing of /home/bjorn/reproduce.py It seems not all file lines were tokenized for comment checking. 
```

**Comment by MiWeiss** [comment]
Successfully reproduced! Thank you.

It's a strange issue: With up to 8 lines in the docstring, it works fine; more lines break it - independent on whether the lines are empty or not. Thus I assume it's somehow related to an AST parsing. May I ask you what you use these empty lines for?

Not sure when I'll find the time to investigate this in detail, but I hope it is soon :-)

**Workaround 1 (suggested):** Adding a docstr to class A solves the problem, as `docstr-coverage` then does not check for an ignore comment above the class def.
```
class A:
    """ The first class in the alphabet. """
    pass
```

**Workaround 2:** Inline-ignore the class def of class A (has same effect as workaround 1)
```
# docstr-coverage: ignored `workaround for issue 79`
class A:
    pass
```

You could probably also fix it by ignoring the classdef using the ignore config, e.g. in a `.docstr.yaml` file. But I did not test that.

**Comment by bjornconstructors** [comment]
@MiWeiss Thanks for your answer. Indeed, I solved it now by adding an exclusion in `.docstr.yaml` but preferably I would not need to do that. The issue is that in our codebase we have 1 very big docstring comment in a file, which causes the above crash.

No rush needed for the fix, since we can workaround it :).

**Comment by MiWeiss** [comment]
@bjornconstructors Thanks. I thought you were actually using the empty docstring, which is something I've never seen anywhere, so I was curious.

I just checked the problem in-depth and it appears the `AssertionError` was a false alert. The PR to fix that is open, we hopefully get it released soon :-)

**Comment by HunterMcGushion** [comment]
Thank you, @bjornconstructors for reporting this and helping @MiWeiss reproduce and fix the issue!
@MiWeiss, thank you for your (always) excellent work and prompt response!
